import datetime
from decimal import *

correctanswers = ["" for i in range(0, 11)]

correctanswers[0] = [('ATL','Atlanta             '),('BOS','Boston              '),('ORD','Chicago             '),('DFW','Dallas-Fort Worth   '),('DEN','Denver              '),('FLL','Fort Lauderdale     '),('LAX','Los Angeles         '),('JFK','New York            '),('OAK','Oakland             '),('IAD','Washington          ')]

correctanswers[1] = [('Anthony Allen                 ',), ('Anthony Edwards               ',), ('Anthony Evans                 ',), ('Anthony Garcia                ',), ('Anthony Gonzalez              ',), ('Anthony Harris                ',), ('Brian Evans                   ',), ('Brian Gonzalez                ',), ('Charles Brown                 ',), ('Charles Evans                 ',), ('Charles Garcia                ',), ('Charles Hall                  ',), ('Christopher Davis             ',), ('Christopher Hernandez         ',), ('Christopher Hill              ',), ('Edward Baker                  ',), ('Edward Evans                  ',), ('Elizabeth Baker               ',), ('Elizabeth Collins             ',), ('Elizabeth Gonzalez            ',), ('Elizabeth Harris              ',), ('Elizabeth Hill                ',)]

correctanswers[2] = [('cust12    ', 'Betty Brown                   ', datetime.date(1975, 8, 14), 'UA'), ('cust39    ', 'Daniel Garcia                 ', datetime.date(1986, 9, 13), 'UA'), ('cust41    ', 'Daniel Hall                   ', datetime.date(1989, 8, 4), 'UA'), ('cust50    ', 'David Hall                    ', datetime.date(1969, 12, 2), 'UA'), ('cust52    ', 'David Hill                    ', datetime.date(1989, 11, 23), 'UA'), ('cust54    ', 'Deborah Allen                 ', datetime.date(1988, 8, 17), 'UA'), ('cust113   ', 'James Green                   ', datetime.date(1977, 9, 16), 'UA'), ('cust116   ', 'Jason Carter                  ', datetime.date(1987, 8, 4), 'UA')]

correctanswers[3] = [('SW', 14), ('UA', 8), ('AA', 4), ('DL', 4)]

correctanswers[4] = [('Anthony Harris                ',), ('Betty Brown                   ',), ('Daniel Garcia                 ',), ('Daniel Hall                   ',), ('David Hall                    ',), ('David Hill                    ',), ('Deborah Adams                 ',), ('Deborah Allen                 ',), ('Donald Adams                  ',), ('Donald Allen                  ',), ('Donna Allen                   ',), ('Dorothy Collins               ',), ('George Collins                ',), ('James Green                   ',), ('Jason Carter                  ',)]

correctanswers[5] = [('Anthony Allen                 ', 14), ('Anthony Edwards               ', 8), ('Anthony Gonzalez              ', 7), ('Betty Gonzalez                ', 7), ('Barbara Collins               ', 6), ('Christopher Davis             ', 6), ('Anthony Harris                ', 5), ('Barbara Hall                  ', 5), ('Betty Edwards                 ', 5), ('Brian Evans                   ', 4), ('Charles Garcia                ', 4), ('Barbara Davis                 ', 3), ('Brian Gonzalez                ', 3), ('David Adams                   ', 3), ('Barbara Gonzalez              ', 2), ('Carol Evans                   ', 2), ('Anthony Evans                 ', 1), ('Barbara Harris                ', 1)]

correctanswers[6] = [('General Edward Lawrence Logan International                                                         ', Decimal('0.40')), ("Chicago O'Hare International                                                                        ", Decimal('0.33')), ('Fort Lauderdale Hollywood International                                                             ', Decimal('0.33')), ('Los Angeles International                                                                           ', Decimal('0.33')), ('Washington Dulles International                                                                     ', Decimal('0.29')), ('Denver International                                                                                ', Decimal('0.20')), ('Hartsfield Jackson Atlanta International                                                            ', Decimal('0.14')), ('Dallas Fort Worth International                                                                     ', Decimal('0.00')), ('John F Kennedy International                                                                        ', Decimal('0.00')), ('Metropolitan Oakland International                                                                  ', Decimal('0.00'))]

correctanswers[7] = [('Barbara Collins               ',), ('Betty Edwards                 ',), ('Carol Evans                   ',), ('Charles Evans                 ',)]

correctanswers[8] = [('Dorothy Carter                ', datetime.date(2016, 8, 5), datetime.date(2016, 8, 8))]

correctanswers[9] = [('SW120 ', 'SW161 ', 'OAK', 'OAK', datetime.timedelta(seconds=3900)), ('SW125 ', 'SW156 ', 'DFW', 'DFW', datetime.timedelta(seconds=4200)), ('AA166 ', 'AA172 ', 'OAK', 'DFW', datetime.timedelta(seconds=5760)), ('SW125 ', 'SW170 ', 'DFW', 'OAK', datetime.timedelta(seconds=6960))]

correctanswers[10] = [('Brian Evans                   ', 1), ('Anthony Edwards               ', 1), ('Donald Allen                  ', 3), ('Betty Gonzalez                ', 4), ('Carol Baker                   ', 5), ('Betty Brown                   ', 5), ('Daniel Baker                  ', 5), ('Anthony Harris                ', 8), ('Charles Garcia                ', 8), ('Edward Brown                  ', 10)]